namespace sarduMatrix {
    // Simple white graphics keep the block selector usable before custom
    // graphics are generated by the external editor.
    //% fixedInstance block="white 8 x 8" blockIdentity="sarduMatrix._graphicPicker"
    export const graphicWhite8x8 = graphicFromBuffer(hex`534d473108080101ffffffffffffffffffffff`);

    //% fixedInstance block="white 16 x 16" blockIdentity="sarduMatrix._graphicPicker"
    export const graphicWhite16x16 = graphicFromBuffer(hex`534d473110100101ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`);

    //% fixedInstance block="white 32 x 8" blockIdentity="sarduMatrix._graphicPicker"
    export const graphicWhite32x8 = graphicFromBuffer(hex`534d473120080101ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`);

    //% fixedInstance block="white 8 x 32" blockIdentity="sarduMatrix._graphicPicker"
    export const graphicWhite8x32 = graphicFromBuffer(hex`534d473108200101ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff`);

    //% fixedInstance block="white 16 x 8" blockIdentity="sarduMatrix._graphicPicker"
    export const graphicWhite16x8 = graphicFromBuffer(hex`534d473110080101ffffffffffffffffffffffffffffffffffffff`);

    //% fixedInstance block="white 8 x 16" blockIdentity="sarduMatrix._graphicPicker"
    export const graphicWhite8x16 = graphicFromBuffer(hex`534d473108100101ffffffffffffffffffffffffffffffffffffff`);
}
