# Generated by MakeCode from the candidate's blocks.
matrix = sarduMatrix.create_modules(6, MatrixModuleType.MATRIX16X16, DigitalPin.P1, 128)

def on_forever():
    matrix.draw_text("Ciao",
        0,
        0,
        neopixel.colors(NeoPixelColors.WHITE),
        MatrixFont.SARDU,
        MatrixFontSize.X1,
        128,
        MatrixTextOrientation.NORMAL)
    matrix.show()
    sarduMatrix.add_scrolling_circle(matrix, 4, 7, neopixel.colors(NeoPixelColors.WHITE), 1)
    sarduMatrix.add_scrolling_rectangle(matrix, 8, 8, 0, neopixel.colors(NeoPixelColors.WHITE), 1)
basic.forever(on_forever)
