# Generated by MakeCode from the candidate's blocks.
matrix = sarduMatrix.create_modules(6, MatrixModuleType.MATRIX16X16, DigitalPin.P1, 128)

def on_forever():
    matrix.draw_text("Ciao",
        0,
        0,
        neopixel.colors(NeoPixelColors.WHITE),
        MatrixFont.SARDU,
        MatrixFontSize.X1,
        128,
        MatrixTextOrientation.NORMAL)
    matrix.show()
basic.forever(on_forever)
